# Generated by Django 5.1 on 2025-11-06 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('nivel', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('bandera_img', models.ImageField(blank=True, null=True, upload_to='banderas/')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ap_paterno', models.CharField(max_length=100)),
                ('ap_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('id_idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='app_Centro_Idiomas.idioma')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('nivel', models.CharField(choices=[('Básico A1', 'Básico A1'), ('Básico A2', 'Básico A2'), ('Intermedio B1', 'Intermedio B1'), ('Intermedio B2', 'Intermedio B2'), ('Avanzado C1', 'Avanzado C1'), ('Avanzado C2', 'Avanzado C2')], max_length=50)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_idioma', to='app_Centro_Idiomas.idioma')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='app_Centro_Idiomas.profesor')),
            ],
        ),
    ]
